language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.2
      env: TOXENV=py32

    - os: linux
      sudo: required
      python: 3.3
      env: TOXENV=py33

    - os: osx
      language: generic
      env: TOXENV=py32

    - os: osx
      env: TOXENV=py33

env:
- TST_DWNL = './tst_dwnl.sh' TST_REPR = './tst_repr.sh'

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "I am doing LINUX!"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "I am doing osx!"; fi

- echo "TTT"
- uname -a
- echo $TRAVIS_OS_NAME
- echo $TRAVIS_BUILD_DIR
- python --version

install:
- pwd
  
script:
- cd tst
- echo $TST_DWNL && $TST_DWNL
- echo $TST_REPR && $TST_REPR
