language: python

os:
  - linux
  - osx
    
#matrix:
#  incude:
#    - os: linux
#      sudo: required
#      env: TOXENV=py32
#      python: 3.2
#
#    - os: osx
#      language: generic
#      env: TOXENV=py32
#
#      #env:
#      #- TST_DWNL = './tst_dwnl.sh' TST_REPR = './tst_repr.sh'

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "I am doing LINUX!"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "I am doing osx!"; fi

- echo "TTT"
- uname -a
- echo $TRAVIS_OS_NAME
- pwd
- echo $TRAVIS_BUILD_DIR
- echo "Hello"

install:
- cd tst
- cd ..
  
script:
- cd tst
- chmod +x tst_dwnl.sh
- chmod +x tst_repr.sh
- ./tst_dwnl.sh
- ./tst_repr.sh
