language: generic

matrix:
  include:
    - os: linux
      sudo: required
      env: TOXENV=py32
      python: 3.2

    - os: osx
      language: generic
      env: TOXENV=py32

env:
- TST_DWNL = './tst_dwnl.sh' TST_REPR = './tst_repr.sh'

before_install:
- pwd
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "I am doing LINUX!"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "I am doing osx!"; fi

- echo "TTT"
- uname -a
- echo $TRAVIS_OS_NAME
- echo $TRAVIS_BUILD_DIR
- python3 --version
- python --version

install:
- cd tst
- pwd
- cd ..
- pwd
  
script:
- cd tst
- pwd
- chmod +x tst_dwnl.sh
- chmod +x tst_repr.sh
- echo $TST_DWNL && $TST_DWNL
- echo $TST_REPR && $TST_REPR
