language: generic


matrix:
    incude:
        - os: linux
          sudo: required
        - os: osx
    allow_failures:
        - os: osx
  
script:
  - echo $TRAVIS_OS_NAME 
  - cd tst
  - chmod +x tst_dwnl.sh
  - chmod +x tst_repr.sh
  - ./tst_dwnl.sh
  - ./tst_repr.sh
