language: generic

matrix:
  incude:
    - os: linux
      sudo: required
    - os: osx
  allow_failures:
    - os: osx

env:
- TST_DWNL = './tst_dwnl.sh' TST_REPR = './tst_repr.sh'

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "I am doing LINUX!"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "I am doing osx!"; fi

- echo "TTT"
- uname -a
- echo $TRAVIS_OS_NAME
- pwd
- echo $TRAVIS_BUILD_DIR
- echo "Hello"

script:
  - cd tst
  - chmod +x tst_dwnl.sh
  - chmod +x tst_repr.sh
  - ./tst_dwnl.sh
  - ./tst_repr.sh
